name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change Directory
      run: cd Data_Structures/DynamicArray/
    - name: make DynamicArrayTest
      run: make -f DynamicArrayTestmake.mk
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
